### ISSUE TITLE
Unable to compute aspect

### ISSUE THREAD

**Issue by MaxDragonheart** [makepath/xarray-spatial#662] opened 2022-02-18 15:44 UTC
Like #661 I see a similar error if I try to compute aspect:
```
import rioxarray as rxr
from xrspatial.aspect import aspect

raster = rxr.open_rasterio(filename=raster_in)
output = aspect(raster)
```
Response:
```
tmp_path = PosixPath('/tmp/pytest-of-max/pytest-15/test_compute_aspect0')

    def test_compute_aspect(tmp_path: Path) -> None:
        print('test_compute_aspect')
        output_path = str(tmp_path)
    
>       compute_aspect(
            raster_in=data,
            output_folder=output_path
        )

dem.py:25: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../drakonotebook/analysis/dem/dem.py:32: in compute_aspect
    output = aspect(raster)
/home/max/.cache/pypoetry/virtualenvs/drakonotebook-Mbf4coiv-py3.8/lib/python3.8/site-packages/xrspatial/aspect.py:260: in aspect
    out = mapper(agg)(agg.data)
/home/max/.cache/pypoetry/virtualenvs/drakonotebook-Mbf4coiv-py3.8/lib/python3.8/site-packages/numba/core/dispatcher.py:415: in _compile_for_args
    error_rewrite(e, 'typing')
/home/max/.cache/pypoetry/virtualenvs/drakonotebook-Mbf4coiv-py3.8/lib/python3.8/site-packages/numba/core/dispatcher.py:358: in error_rewrite
    reraise(type(e), e, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

tp = <class 'numba.core.errors.TypingError'>
value = TypingError('Failed in nopython mode pipeline (step: nopython frontend)\nInternal error at <numba.core.typeinfer.Exhau...4:\ndef _run_numpy(data: np.ndarray):\n    <source elided>\n    out[:] = np.nan\n    rows, cols = data.shape\n    ^\n')
tb = None

    def reraise(tp, value, tb=None):
        if value is None:
            value = tp()
        if value.__traceback__ is not tb:
>           raise value.with_traceback(tb)
E           numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
E           Internal error at <numba.core.typeinfer.ExhaustIterConstraint object at 0x7f69e28a3550>.
E           wrong tuple length for '$46load_attr.20': expected 2, got 3
E           During: typing of exhaust iter at /home/max/.cache/pypoetry/virtualenvs/drakonotebook-Mbf4coiv-py3.8/lib/python3.8/site-packages/xrspatial/aspect.py (34)
E           Enable logging at debug level for details.
E           
E           File "../../../../../../.cache/pypoetry/virtualenvs/drakonotebook-Mbf4coiv-py3.8/lib/python3.8/site-packages/xrspatial/aspect.py", line 34:
E           def _run_numpy(data: np.ndarray):
E               <source elided>
E               out[:] = np.nan
E               rows, cols = data.shape
E               ^

/home/max/.cache/pypoetry/virtualenvs/drakonotebook-Mbf4coiv-py3.8/lib/python3.8/site-packages/numba/core/utils.py:80: TypingError
```
[Here](https://drive.google.com/file/d/1Ptgrd9P4mujWxOpclWfOi523g3VMZtDh/view?usp=sharing) the sample DEM.

**Comment by ianthomas23** [comment] 2022-02-18 16:09
Duplicate of #661.

**Closed as completed by ianthomas23** 2022-02-18 16:09 UTC
