### ISSUE TITLE
nodata_value for zonal_stats doesn't appear to work

### ISSUE THREAD

**Issue by petersedivec** [makepath/xarray-spatial#597] opened 2021-12-15 09:08 UTC
**Describe the bug**
Running zonal_stats and passing in the argument `nodata_values = -99999` results in a 
ValueError: All arrays must be of the same length
stack trace with method and line number
zonal.py line 519
zonal.py 335
python3.7/site-packages/pandas/core/frame.py 614
python3.7/site-packages/pandas/core/internals/construction.py  465

When i run zonal_stats without the `nodata_values` argument it runs fine and computes

`nodata_values = -99999` or `nodata_values = -99999.0`

**Expected behavior**
Would expect the method zonal_stats to return statistics computed ignoring pixels with nodata_values

**Screenshots**
Unable to provide screenshots, running this in a classified environment

**Desktop (please complete the following information):**
Running this in Databricks 7.3LTS with Python 3.7.5, xarray-spatial 0.3.0

**Comment by thuydotm** [comment] 2021-12-15 13:07
Thanks for reaching out. I guess the error happened because, in the `values` raster, there is some zone filled with `nodata_values`. This bug has already been fixed with PR https://github.com/makepath/xarray-spatial/pull/581, and we plan to add this to the next release in early January. 

In the meanwhile, can you try to replace all `nodata_values` pixels in `values` raster by `np.nan` and run the analysis as a temporary workaround? This should work because all NaNs will be excluded from calculations.

**Comment by petersedivec** [comment] 2021-12-15 14:43
thanks, yep, from looking through the code we noticed that.  We also ran with a positive value of 99999 and that worked fine so something with negative sign is causing a bug

**Comment by thuydotm** [comment] 2021-12-16 17:23
Did the 2 datasets you run are exactly the same except for the nodata value? It could happen that the dataset with a positive value of 99999 does not have a zone that only filled by nodata. If this is not the case, can you please add a minimal reproducible example where positive works and negative doesn't? Off the top of my head, I don't find any reason that it behaves differently with negative sign.

**Comment by petersedivec** [comment] 2021-12-16 21:47
Good point, I don't think there were any positive values in the array with
99999 so maybe that's why the case worked. I haven't had a chance to swap
out for Nan but I will test both cases when I'm back from the holidays.

**Comment by thuydotm** [comment] 2022-11-28 04:47
Fixed in https://github.com/makepath/xarray-spatial/pull/581/files

**Closed by thuydotm** 2022-11-28 04:47 UTC
Labels: bug
